# Enable LoRa mock driver
CONFIG_LORA_MOCK=y

CONFIG_TEST_RANDOM_GENERATOR=y

# https://github.com/zephyrproject-rtos/zephyr/issues/67073
CONFIG_QEMU_ICOUNT=n

# Flash simulator for NVS-backed config persistence
CONFIG_FLASH_SIMULATOR=y
CONFIG_FLASH_SIMULATOR_DOUBLE_WRITES=y

