#ifndef TS_VERSION_H
#define TS_VERSION_H

#define FIRMWARE_VERSION_MAJOR 0
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 1
#define FIRMWARE_VERSION_STRING "0.0.1"

#define BUILD_TIMESTAMP __DATE__ " " __TIME__
#define GIT_COMMIT_HASH "@GIT_COMMIT_HASH@"

#define FIRMWARE_VERSION_NUMERIC                                      \
    ((FIRMWARE_VERSION_MAJOR << 16) | (FIRMWARE_VERSION_MINOR << 8) | \
     FIRMWARE_VERSION_PATCH)

#endif  // TS_VERSION_H